name: DockerCD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 저장소 Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3  # 사용할 버전 명시인데 공식문서를 확인해 봐야함
        with:
          java-version: 17
          distribution: temurin

      - name: 스프링부트 애플리케이션 빌드 # (1)
        run: ./gradlew build -Pjasypt.encryptor.password=${{secrets.JASYPT_ENCRYPTOR_PASSWORD}}

      - name: Docker Hub 로그인 # (2)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 도커 이미지 빌드 # (3)
        run: docker build -t ${{ secrets.DOCKERHUB_IMAGE_NAME }} .

      - name: tag 설정 # (4)
        run: docker tag ${{ secrets.DOCKERHUB_IMAGE_NAME }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}

      - name: Docker Hub 퍼블리시 # (5)
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}

  deploy:
    needs: build
    name: Deploy
    runs-on: [ self-hosted, label-sp ]
    steps:
      - name: deploy run
        run: |
          sh /home/ubuntu/dep/docker/run.sh
#          host: ${{ secrets.WAS_HOST }}
#          username: ${{ secrets.WAS_USERNAME }}
#          password: ${{ secrets.WAS_PASSWORD }}
#          port: ${{ secrets.WAS_SSH_PORT }}
#          script: |
#            docker stop $(docker ps -a -q)
#            docker rm $(docker ps -a -q)
#            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}
#            docker run -d --name=test -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_IMAGE_NAME }}